### ISSUE TITLE
show user ONLY their own calender

### ISSUE THREAD

**Issue by losferatos** [sproctor/php-calendar#165]
Hi there!

I highly appreciate your work guys. I just started an internship and my boss wants me to implement such a calender option. 
But because there are hundreds of users and therefore also hundreds of calenders. To keep it slick for the users I'd like to put a limitation on - so that they can only pick their calender from the dropdown and don't have to go through the whole list.

I'm looking for some hint on how I can archive this. I haven't even managed to determine where the dropdown is created.
Any help is highly appreciated =)

best regards (and sorry, I'm not a native english speaker)
Eric

**Comment by sproctor** [comment]
It's been a while since I've worked on this.

The calendar list is created here: https://github.com/sproctor/php-calendar/blob/d8e71bfa29a237035580a27cd744ac3c063903ac/includes/calendar.php#L794

That should probably have the following in the loop:

```php
if ($calendar->can_read()) {
    $list[$phpc_home_url . '?phpcid=' . $calendar->get_cid()] = $calendar->get_title();
}
```

That might accomplish what you're attempting, depending on whether users have read access to other's calendars.

**Comment by losferatos** [comment]
Thank you so much for your fast and perfect answer!

Again, highly appreciated =)

**Comment by sproctor** [comment]
committed this change. closing issue
